### ISSUE TITLE
Compilation errors with clang and gcc using C++20

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#410]
Commit `1f9a845a4` fails to compile with clang-10.0.1 with `--std=c++20`. There are errors in `iterator.hpp` due to changes to the `operator==` semantics (which are easily fixed) and  in pybind11-2.3 (which may be hard to fix). 
Compilation succeeds with g++-10.0.1, so I'm not sure if the clang-10.0.1 behaviour is correct.
There are also warnings in both compilers due to deprecated use of `volatile`. We should check if rounding is correctly handled with the new compilers.

**Comment by lgeretti** [comment]
I realized just yesterday that it fails on the CI. It doesn't on AppleClang, so this passed below my radar. Do you want me to roll back the version for the time being?

I can try to address the pybind11 issues by upgrading it, if you haven't already tried this manually yourself.

**Comment by pietercollins** [comment]
I tried upgrading to pybind11-2.5, and the problem remains. The issue is at lines 291 and 292 of `cast.h`, in which the member function is not declared `const`. Changing to
```
        bool operator==(const iterator &other) const { return curr.index == other.curr.index; }
        bool operator!=(const iterator &other) const { return curr.index != other.curr.index; }
```
fixed the problem.

I will file a bug report to pybind11. 

Can we ship the patched pybind11 for now with Ariadne?

**Comment by lgeretti** [comment]
Even better, if we produce a patch file we can apply it in the CMake configuration. When this is fixed upstream we drop the patch.

**Comment by pietercollins** [comment]
I checked the pybind11 library, and they've already fixed the problem in `master`.

**Comment by lgeretti** [comment]
Ok then you can change the pybind checkout commit in the main CMakeLists.txt file directly.

**Comment by pietercollins** [comment]
Fixed comparison errors and `volatile` warnings. Updated pybind11 to current master.
